### ISSUE TITLE
Unable to see animations

### ISSUE THREAD

**Issue by kysomers** [MakeSchool-Tutorials/Intro-Variables-Swift-Playground#13]
Not sure if it's an issue on my end or not, but no animations are appearing on any of the 6 parts for me.

**Comment by dionlarson** [comment]
Did you open the assistant window? Sorry, should have given a better introduction to this since you are not accessing it from the academy. Click the joined circles and it should open the timeline.

**Comment by kysomers** [comment]
Yeah, that's what I needed to do. It works fine.
