### ISSUE TITLE
P4 - Crush the Block III

### ISSUE THREAD

**Issue by zontan** [MakeSchool-Tutorials/Intro-Variables-Swift-Playground#14]
In the "Did that work?" section, the following line exists: "The spaces around the plus operator need to be there for the computer to correctly compute the value!"

This is a lie. I like spaces as much as the next guy, but do we really want to be telling people the compiler requires it when it's just a coding convention? Especially since people can just test it themselves and find otherwise?

**Comment by dionlarson** [comment]
Thoughts on how to cleanly explain `1+1` and `1 + 1` works but not `1 +1` or `1+ 1`?

**Comment by zontan** [comment]
Something like, "You need spaces on both sides or neither - putting a space only on one side won't work", maybe. I don't think it's a good place to go into exactly why that's true, but that should be clear enough. Possibly a note that they don't need to understand why just yet.
