### ISSUE TITLE
P2 claims that we used "var distanceFromLeft: Int = 50" to create "distanceFromLeft" whereas we actually used "var distanceFromLeft = 50"

### ISSUE THREAD

**Issue by danstepanov** [MakeSchool-Tutorials/Intro-Variables-Swift-Playground#8]
```
We created distanceFromLeft with the line

var distanceFromLeft: Int = 50

We already know var is the keyword for creating a variable.
```

whereas, we actually used the line:

`var distanceFromLeft = 50`

**Comment by dionlarson** [comment]
Not an issue?

https://github.com/MakeSchool-Tutorials/Intro-Variables-Swift-Playground/blob/master/Variables.playground/Pages/02-Crush-The-Block-I.xcplaygroundpage/Contents.swift#L11
